apiVersion: apps/v1
kind: Deployment
metadata:
        name: unam-deployment
        namespace: utilitaire-nam
spec:
        replicas: 3
        selector:
                matchLabels:
                        app: uname-service
        template:
                metadata:
                        labels:
                                app: uname-service
                spec:
                        containers:
                                - name: uname-service
                                  image: nexus3.inspq.qc.ca:5000/inspq/utilitaire-nam-service:latest
                                  ports:
                                          - containerPort: 80
                                          
