apiVersion: v1
kind: Service
metadata:
        name: unam-deployment
spec:
        selector:
                app: unam-service
        type: NodePort
        ports:
                - port: 80
                  targetPort: 80
                  nodePort: 31001
