---
- hosts: unam
  vars:
    unamservice_internal_port: 8080
    unamservice_internal_actuator_port: 28081
    cert_file_path: /etc/pki/tls/certs
    cert_key_path: /etc/pki/tls/private
    docker_registry: nexus3.inspq.qc.ca:5000
    unamservice_container_name: "unamservice{{ env | lower }}"
    unamservice_artifact_id: utilitaire-nam-service
    unamservice_docker_image: "{{ docker_registry }}/inspq/{{ unamservice_artifact_id }}"
    unamservice_port_mappers:
      - "{{ unamservice_external_port }}:{{ unamservice_internal_port }}"
      - "{{ unamservice_external_actuator_port }}:{{ unamservice_internal_actuator_port }}"
    unamservice_container_env:
      "LOG4J2_GRAYLOG_URL": "{{ unam_graylog_host | default() }}"
      "LOG4J2_GRAYLOG_PORT_GELF_UDP": "{{ unam_graylog_port_gelf_udp | default() | string }}"
      "GRAYLOG_HOST_BASE": "{{ unamservice_container_name }}"
      "DEBUG_PORT": "{{ unamservice_debug_port | default('0') }}"
          
  roles:
  - name: application_web_docker
    application_docker_image: "{{ unamservice_docker_image }}"
    application_container_name: "{{ unamservice_container_name }}"
    application_external_port: "{{ unamservice_external_port }}"
    application_port_mappers: "{{ unamservice_port_mappers }}"
    application_image_version: "{{ unamservice_image_version }}"
    application_container_env: "{{ unamservice_container_env }}"
    application_graylog_host: "{{ unam_graylog_host | default() }}"
    application_graylog_port_gelf_udp: "{{ unam_graylog_port_gelf_udp | default() }}"
    application_protocol: "{{ unamservice_protocol | default() }}"
    application_virtualhost_protocol: "{{ unamservice_virtualhost_protocol | default() }}"
    application_base_url: "{{ unamservice_base_url | default() }}"