server:
  port: 8080
  forward-headers-strategy: framework
management:
  server:
    port: 28081
    address: 0.0.0.0
  endpoint:
    shutdown:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
