---
apiVersion: v1
kind: Namespace
metadata:
  name: unam
  labels:
    istio-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: unam
  name: unam-deployment
  labels:
    app: unam-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unam-service
  template:
    metadata:
      labels:
        app: unam-service
    spec:
      containers:
      - name: unam-service
        image: nexus3.inspq.qc.ca:5000/inspq/utilitaire-nam-service:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: unam
  name: unam-service
  labels:
    serviceapp: actuator
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "28081"
spec:
  selector:
    app: unam-service
  ports:
    - name: web
      protocol: TCP
      port: 14101
      targetPort: 8080
    - name: actuator
      protocol: TCP
      port: 27082
      targetPort: 28081
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: unam
  name: unam-service
  labels:
    account: unam
    
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: unam
  name: ingress-unam
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: kubeunam.laboinspq.qc.ca
    http:
      paths:
      - path: /
        backend:
          serviceName: unam-service
          servicePort: 14101
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: unam
  name: ingress-istio-unam
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: kubeunam.laboinspq.qc.ca
    http:
      paths:
      - path: /
        backend:
          serviceName: istio-ingressgateway
          servicePort: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: unam
  name: actuator
  labels:
    release: istio
spec:
  selector:
    matchLabels:
      serviceapp: actuator
  endpoints:
  - port: actuator
    path: '/actuator/prometheus'
    interval: 15s
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: unam
  name: unam-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "kubeunam-labo.santepublique.rtss.qc.ca"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: unam
  name: unam-virtual-service
spec:
  hosts:
  - "kubeunam-labo.santepublique.rtss.qc.ca"
  gateways:
  - unam-gateway
  http:
  - match:
    - uri:
        prefix: /nam/valider
    - uri:
        prefix: /nam/genrer
    - uri:
        prefix: /nam/info

    route:
    - destination:
        host: unam-service
        port:
          number: 14101