---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unam-deployment
  labels:
    app: unam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unam
  template:
    metadata:
      labels:
        app: unam
    spec:
      containers:
      - name: unam
        image: nexus3.inspq.qc.ca:5000/inspq/utilitaire-nam-service:0.8.2-SNAPSHOT
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: unam-service
spec:
  selector:
    app: unam
  ports:
    - protocol: TCP
      port: 14050
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-unam
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: kubeunam.laboinspq.qc.ca
    http:
      paths:
      - path: /
        backend:
          serviceName: unam-service
          servicePort: 14050
